### ISSUE TITLE
grammatical nit

### ISSUE THREAD

**Issue by kmdawson** [iainctduncan/learn-scheme-for-max#1]
Not sure this is what you wanted as feedback, being non-technical, but as the book is being written as we speak, I'd like to note that the word 'none' is singular, so the sentence in the second paragraph of the Introduction should read:

The challenge is that, while there are a lot of great, free, on-line resources, none of them targets s7 specifically.

**Comment by iainctduncan** [comment]
Thanks! Corrected.
